name: Bookings Assistant
version: 0.3.0
slug: bookings-assistant
description: Manage scout campsite bookings from OSM
url: https://github.com/piers-williams/bookings-helper
arch:
  - amd64
ports:
  5000/tcp: 8099
ports_description:
  5000/tcp: Web interface
map:
  - data:rw
options:
  osm_base_url: "https://www.onlinescoutmanager.co.uk"
  osm_campsite_id: "219"
  osm_section_id: "56710"
  osm_client_id: ""
  osm_client_secret: ""
schema:
  osm_base_url: url
  osm_campsite_id: str
  osm_section_id: str
  osm_client_id: str
  osm_client_secret: password
image: ghcr.io/piers-williams/bookings-assistant-{arch}
